# Generated by Django 4.0.3 on 2022-04-07 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=150)),
                ('type', models.CharField(default='FL', max_length=2, verbose_name=(('SH', 'SHIPPING'), ('BL', 'BILLING'), ('FL', 'FULL')))),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=150)),
                ('tel', models.CharField(max_length=20)),
                ('imageURL', models.URLField(max_length=500)),
                ('unable', models.BooleanField(default=False)),
                ('addres', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='administrador.address')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('size', models.EmailField(default='AV', max_length=2, verbose_name=(('BG', 'BIG'), ('AV', 'AVERAGE'), ('SM', 'SMALL')))),
                ('weight', models.FloatField(max_length=100)),
                ('price', models.FloatField(max_length=100)),
                ('imageURL', models.URLField(max_length=500)),
                ('unable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField()),
                ('delivery_date', models.DateTimeField()),
                ('unable', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='administrador.clients')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='administrador.orders')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='administrador.products')),
            ],
        ),
    ]
