# Generated by Django 4.0.3 on 2022-04-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_rename_addres_clients_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
