# Generated by Django 4.0.3 on 2022-04-11 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0005_alter_address_type_alter_products_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='address',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='imageURL',
        ),
        migrations.RemoveField(
            model_name='products',
            name='price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='size',
        ),
        migrations.RemoveField(
            model_name='products',
            name='unable',
        ),
        migrations.RemoveField(
            model_name='products',
            name='weight',
        ),
        migrations.AddField(
            model_name='address',
            name='client',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='administrador.clients'),
        ),
        migrations.AddField(
            model_name='orders',
            name='billing_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='billing', to='administrador.address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='shipping_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='shipping', to='administrador.address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order_items',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Products_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('BG', 'BIG'), ('AV', 'AVERAGE'), ('SM', 'SMALL')], default='AV', max_length=2)),
                ('weight', models.FloatField(max_length=100)),
                ('price', models.FloatField(max_length=100)),
                ('unable', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.products')),
            ],
        ),
        migrations.AlterField(
            model_name='order_items',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='administrador.products_details'),
        ),
    ]
