# Generated by Django 4.0.3 on 2022-04-11 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0011_alter_address_client'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='products_details',
            unique_together={('product', 'size')},
        ),
    ]
