# Generated by Django 4.0.3 on 2022-04-13 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0014_alter_products_details_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='type',
        ),
    ]
