# Generated by Django 4.0.3 on 2022-04-15 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0015_remove_address_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='unable',
        ),
        migrations.AlterField(
            model_name='order_items',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.orders'),
        ),
    ]
