# Generated by Django 4.0.3 on 2022-04-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0017_order_items_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='unable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='unable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clients',
            name='email',
            field=models.EmailField(max_length=150, unique=True),
        ),
    ]
